<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Site-wide image slots (admin: Site Images)
    |--------------------------------------------------------------------------
    | setting_key is stored in site_settings. fallback is used when empty.
    | size notes are shown in admin so editors upload the right dimensions.
    */
    'slots' => [
        [
            'key' => 'hero_image',
            'setting_key' => 'hero.image_path',
            'group' => 'Homepage (/)',
            'label' => 'Home hero still image',
            'description' => 'Full-bleed background when hero mode is Image (or video/carousel fallback).',
            'folder' => 'hero',
            'recommended' => '1920 × 1080 px or larger (JPG)',
            'aspect' => '16:9',
            'max_kb' => 5120,
            'fallback_asset' => 'hero.jpg',
            'fallback_config' => 'ctc.hero_image',
            'used_on' => ['Home hero'],
            'public_path' => '/',
            'public_label' => 'Home',
        ],
        [
            'key' => 'home_services',
            'setting_key' => 'home.services_image_path',
            'group' => 'Homepage (/)',
            'label' => 'Our Services panel image',
            'description' => 'Large photo beside “Our Services” on the homepage, and the Clinical care panel on /services.',
            'folder' => 'homepage',
            'recommended' => '1200 × 900 px landscape (JPG/WebP)',
            'aspect' => '4:3',
            'max_kb' => 5120,
            'fallback_asset' => 'service-home.webp',
            'used_on' => ['Home → Our Services', 'Services → Clinical care'],
            'public_path' => '/services',
            'public_label' => 'Services',
        ],
        [
            'key' => 'page_banner_default',
            'setting_key' => 'site_image.page_banner_default',
            'group' => 'Shared defaults',
            'label' => 'Default page header banner',
            'description' => 'Fallback header image for any inner page without its own banner (see Page header banners below).',
            'folder' => 'page-banners',
            'recommended' => '1920 × 800 px (JPG)',
            'aspect' => '~2.4:1',
            'max_kb' => 5120,
            'fallback_config' => 'ctc.page_banner_image',
            'used_on' => ['All inner pages (fallback)'],
        ],
        [
            'key' => 'support_side',
            'setting_key' => 'site_image.support_side',
            'group' => 'Support page (/support)',
            'label' => 'Support the CTC — side image',
            'description' => 'Tall photo on the right of the Donate / Sponsor / Equipment / Partner cards on Support the CTC.',
            'folder' => 'support',
            'recommended' => '900 × 1200 px (JPG)',
            'aspect' => '3:4',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.page_banner_image',
            'used_on' => ['Support the CTC'],
            'public_path' => '/support',
            'public_label' => 'Support the CTC',
        ],
        [
            'key' => 'logo',
            'setting_key' => 'site_image.logo',
            'group' => 'Brand',
            'label' => 'Site logo',
            'description' => 'Navbar and college application header.',
            'folder' => 'site',
            'recommended' => '512 × 512 px (PNG, transparent)',
            'aspect' => '1:1',
            'max_kb' => 2048,
            'fallback_asset' => 'logo-ctc.png',
            'used_on' => ['All pages (navbar)', '/college/apply'],
            'public_path' => '/',
            'public_label' => 'Home',
        ],
        [
            'key' => 'flagship',
            'setting_key' => 'site_image.flagship',
            'group' => 'Brand',
            'label' => 'Flagship mark / favicon',
            'description' => 'Browser tab icon (and legacy brand mark).',
            'folder' => 'site',
            'recommended' => '256–512 × 256–512 px (PNG)',
            'aspect' => '1:1',
            'max_kb' => 1024,
            'fallback_asset' => 'flagship.png',
            'used_on' => ['Browser tab icon'],
            'public_path' => '/',
            'public_label' => 'Home',
        ],
        [
            'key' => 'og',
            'setting_key' => 'site_image.og',
            'group' => 'Brand',
            'label' => 'Social / Open Graph image',
            'description' => 'Default image when pages are shared on Facebook, X, WhatsApp, etc.',
            'folder' => 'site',
            'recommended' => '1200 × 630 px (JPG)',
            'aspect' => '1.91:1',
            'max_kb' => 3072,
            'fallback_asset' => 'ctc.jpg',
            'used_on' => ['SEO / social previews'],
        ],
        [
            'key' => 'placeholder_facility',
            'setting_key' => 'about.who_we_are.image_main_path',
            'legacy_setting_keys' => ['site_image.placeholder.facility'],
            'group' => 'About page (/about)',
            'label' => 'Who we are — main image',
            'description' => 'Large photo beside the “Who we are” text on the About page.',
            'folder' => 'about',
            'recommended' => '1200 × 900 px (JPG)',
            'aspect' => '4:3',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.facility',
            'used_on' => ['About → Who we are'],
            'public_path' => '/about',
            'public_label' => 'About CTC',
        ],
        [
            'key' => 'placeholder_team',
            'setting_key' => 'about.who_we_are.image_side_1_path',
            'legacy_setting_keys' => ['site_image.placeholder.team'],
            'group' => 'About page (/about)',
            'label' => 'Who we are — top-right image',
            'description' => 'Upper small photo in the Who we are collage on the About page.',
            'folder' => 'about',
            'recommended' => '800 × 800 px (JPG)',
            'aspect' => '1:1',
            'max_kb' => 3072,
            'fallback_config' => 'ctc.placeholder_images.team',
            'used_on' => ['About → Who we are'],
            'public_path' => '/about',
            'public_label' => 'About CTC',
        ],
        [
            'key' => 'placeholder_care',
            'setting_key' => 'about.who_we_are.image_side_2_path',
            'legacy_setting_keys' => ['site_image.placeholder.care'],
            'group' => 'About page (/about)',
            'label' => 'Who we are — bottom-right image',
            'description' => 'Lower small photo in the Who we are collage. Also used as a fallback on service-area pages when needed.',
            'folder' => 'about',
            'recommended' => '800 × 800 px (JPG)',
            'aspect' => '1:1',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.care',
            'used_on' => ['About → Who we are', 'Services category fallback'],
            'public_path' => '/about',
            'public_label' => 'About CTC',
        ],
        [
            'key' => 'about_purpose',
            'setting_key' => 'about.purpose.right.image_path',
            'group' => 'About page (/about)',
            'label' => 'Purpose panel image',
            'description' => 'Photo on the Mission & Vision / Purpose Statement section of the About page.',
            'folder' => 'about',
            'recommended' => '1000 × 1200 px (JPG)',
            'aspect' => '5:6',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.care',
            'used_on' => ['About → Purpose'],
            'public_path' => '/about',
            'public_label' => 'About CTC',
        ],
        [
            'key' => 'placeholder_story',
            'setting_key' => 'site_image.placeholder.story',
            'group' => 'Shared defaults',
            'label' => 'Story / impact fallback',
            'description' => 'Fallback for impact and story imagery when a dedicated photo is missing.',
            'folder' => 'placeholders',
            'recommended' => '1200 × 800 px (JPG)',
            'aspect' => '3:2',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.story',
            'used_on' => ['Impact (fallback)'],
            'public_path' => '/impact',
            'public_label' => 'Impact',
        ],
    ],

    /*
    | Content areas that already have their own image uploads (shown as links).
    */
    'content_managers' => [
        ['label' => 'Page header banners (per page)', 'route' => 'admin-dashboard.page-banners.index', 'note' => 'About, Services, Training, Contact, etc.'],
        ['label' => 'Hero carousel slides', 'route' => 'admin-dashboard.hero.edit', 'hash' => 'carousel-slides', 'note' => 'Homepage carousel images'],
        ['label' => 'Team / specialists photos', 'route' => 'admin-dashboard.team-members.index', 'note' => 'Individual portraits'],
        ['label' => 'Services featured images', 'route' => 'admin-dashboard.services.index', 'note' => 'Service detail pages'],
        ['label' => 'Service area page images', 'route' => 'admin-dashboard.service-category-pages.index', 'note' => 'Cardiac / Thoracic / Diagnostics pages'],
        ['label' => 'News featured images', 'route' => 'admin-dashboard.news.index', 'note' => 'Articles'],
        ['label' => 'Gallery', 'route' => 'admin-dashboard.gallery.index', 'note' => 'Public gallery album'],
        ['label' => 'Impact stories', 'route' => 'admin-dashboard.impact.index', 'note' => 'Impact page photos'],
        ['label' => 'Impact testimonials', 'route' => 'admin-dashboard.impact-testimonials.index', 'note' => 'Testimonial portraits'],
        ['label' => 'About sections', 'route' => 'admin-dashboard.about.index', 'note' => 'About page section media'],
        ['label' => 'Who we are (text + images)', 'route' => 'admin-dashboard.about-intro.edit', 'note' => 'Same collage images as Site Images → About page'],
        ['label' => 'Purpose (text + image)', 'route' => 'admin-dashboard.about-purpose.edit', 'note' => 'Same purpose image as Site Images → About page'],
    ],
];
