<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Site-wide image slots (admin: Site Images)
    |--------------------------------------------------------------------------
    | setting_key is stored in site_settings. fallback is used when empty.
    | size notes are shown in admin so editors upload the right dimensions.
    */
    'slots' => [
        [
            'key' => 'logo',
            'setting_key' => 'site_image.logo',
            'group' => 'Brand',
            'label' => 'Site logo',
            'description' => 'Navbar and college application header.',
            'folder' => 'site',
            'recommended' => '512 × 512 px (PNG, transparent)',
            'aspect' => '1:1',
            'max_kb' => 2048,
            'fallback_asset' => 'logo-ctc.png',
            'used_on' => ['/', 'Navigation', '/college/apply'],
        ],
        [
            'key' => 'flagship',
            'setting_key' => 'site_image.flagship',
            'group' => 'Brand',
            'label' => 'Flagship mark / favicon',
            'description' => 'Hero brand mark and browser tab icon.',
            'folder' => 'site',
            'recommended' => '256–512 × 256–512 px (PNG)',
            'aspect' => '1:1',
            'max_kb' => 1024,
            'fallback_asset' => 'flagship.png',
            'used_on' => ['Home hero', 'Favicon'],
        ],
        [
            'key' => 'og',
            'setting_key' => 'site_image.og',
            'group' => 'Brand',
            'label' => 'Social / Open Graph image',
            'description' => 'Default image when pages are shared on Facebook, X, WhatsApp, etc.',
            'folder' => 'site',
            'recommended' => '1200 × 630 px (JPG)',
            'aspect' => '1.91:1',
            'max_kb' => 3072,
            'fallback_asset' => 'ctc.jpg',
            'used_on' => ['SEO / social previews'],
        ],
        [
            'key' => 'hero_image',
            'setting_key' => 'hero.image_path',
            'group' => 'Homepage',
            'label' => 'Home hero still image',
            'description' => 'Used when hero mode is Image (or when video/carousel falls back).',
            'folder' => 'hero',
            'recommended' => '1920 × 1080 px or larger (JPG)',
            'aspect' => '16:9',
            'max_kb' => 5120,
            'fallback_asset' => 'hero.jpg',
            'fallback_config' => 'ctc.hero_image',
            'used_on' => ['/'],
        ],
        [
            'key' => 'home_services',
            'setting_key' => 'home.services_image_path',
            'group' => 'Homepage',
            'label' => 'Homepage services panel image',
            'description' => 'Large photo on the right of the Our Services section.',
            'folder' => 'homepage',
            'recommended' => '1200 × 1600 px (portrait) or 1200 × 900 (JPG)',
            'aspect' => '3:4 or 4:3',
            'max_kb' => 5120,
            'fallback_asset' => 'service-home.webp',
            'used_on' => ['/# Our Services'],
        ],
        [
            'key' => 'page_banner_default',
            'setting_key' => 'site_image.page_banner_default',
            'group' => 'Defaults',
            'label' => 'Default page header banner',
            'description' => 'Used for any inner page that has no custom page banner.',
            'folder' => 'page-banners',
            'recommended' => '1920 × 800 px (JPG)',
            'aspect' => '~2.4:1',
            'max_kb' => 5120,
            'fallback_config' => 'ctc.page_banner_image',
            'used_on' => ['All inner pages (fallback)'],
        ],
        [
            'key' => 'support_side',
            'setting_key' => 'site_image.support_side',
            'group' => 'Defaults',
            'label' => 'Support page side image',
            'description' => 'Photo on the Support / Donate page.',
            'folder' => 'site',
            'recommended' => '900 × 1200 px (JPG)',
            'aspect' => '3:4',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.page_banner_image',
            'used_on' => ['/support'],
        ],
        [
            'key' => 'placeholder_facility',
            'setting_key' => 'site_image.placeholder.facility',
            'group' => 'Placeholders',
            'label' => 'Placeholder: facility',
            'description' => 'Fallback for About “Who we are” main image and similar.',
            'folder' => 'placeholders',
            'recommended' => '1200 × 800 px (JPG)',
            'aspect' => '3:2',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.facility',
            'used_on' => ['/about'],
        ],
        [
            'key' => 'placeholder_team',
            'setting_key' => 'site_image.placeholder.team',
            'group' => 'Placeholders',
            'label' => 'Placeholder: team',
            'description' => 'Fallback for About side images when empty.',
            'folder' => 'placeholders',
            'recommended' => '800 × 1000 px (JPG)',
            'aspect' => '4:5',
            'max_kb' => 3072,
            'fallback_config' => 'ctc.placeholder_images.team',
            'used_on' => ['/about'],
        ],
        [
            'key' => 'placeholder_care',
            'setting_key' => 'site_image.placeholder.care',
            'group' => 'Placeholders',
            'label' => 'Placeholder: care',
            'description' => 'Fallback for About purpose and service-area placeholders.',
            'folder' => 'placeholders',
            'recommended' => '1200 × 800 px (JPG)',
            'aspect' => '3:2',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.care',
            'used_on' => ['/about', '/services/*'],
        ],
        [
            'key' => 'placeholder_story',
            'setting_key' => 'site_image.placeholder.story',
            'group' => 'Placeholders',
            'label' => 'Placeholder: story',
            'description' => 'Fallback for impact / story imagery when needed.',
            'folder' => 'placeholders',
            'recommended' => '1200 × 800 px (JPG)',
            'aspect' => '3:2',
            'max_kb' => 4096,
            'fallback_config' => 'ctc.placeholder_images.story',
            'used_on' => ['/impact'],
        ],
    ],

    /*
    | Content areas that already have their own image uploads (shown as links).
    */
    'content_managers' => [
        ['label' => 'Page header banners (per page)', 'route' => 'admin-dashboard.page-banners.index', 'note' => 'About, Services, Training, Contact, etc.'],
        ['label' => 'Hero carousel slides', 'route' => 'admin-dashboard.hero.edit', 'hash' => 'carousel-slides', 'note' => 'Homepage carousel images'],
        ['label' => 'Team / specialists photos', 'route' => 'admin-dashboard.team-members.index', 'note' => 'Individual portraits'],
        ['label' => 'Services featured images', 'route' => 'admin-dashboard.services.index', 'note' => 'Service detail pages'],
        ['label' => 'Service area page images', 'route' => 'admin-dashboard.service-category-pages.index', 'note' => 'Cardiac / Thoracic / Diagnostics pages'],
        ['label' => 'News featured images', 'route' => 'admin-dashboard.news.index', 'note' => 'Articles'],
        ['label' => 'Gallery', 'route' => 'admin-dashboard.gallery.index', 'note' => 'Public gallery album'],
        ['label' => 'Impact stories', 'route' => 'admin-dashboard.impact.index', 'note' => 'Impact page photos'],
        ['label' => 'Impact testimonials', 'route' => 'admin-dashboard.impact-testimonials.index', 'note' => 'Testimonial portraits'],
        ['label' => 'About sections', 'route' => 'admin-dashboard.about.index', 'note' => 'About page section media'],
        ['label' => 'Who we are images', 'route' => 'admin-dashboard.about-intro.edit', 'note' => 'About intro collage'],
        ['label' => 'Purpose image', 'route' => 'admin-dashboard.about-purpose.edit', 'note' => 'Mission / vision panel'],
    ],
];
